# Generated by Django 6.0.1 on 2026-03-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('professional_card', models.CharField(max_length=100, null=True)),
                ('specialization', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'Doctor',
            },
        ),
    ]
