# Generated by Django 6.0.1 on 2026-01-31 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='id_doctor',
            new_name='doctor_id',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='especializacion',
            new_name='professional_card',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='tarjeta_profesional',
            new_name='specialization',
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
    ]
