# Generated by Django 6.0.1 on 2026-04-18 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctor',
            table='doctor',
        ),
    ]
