# Generated by Django 6.0.1 on 2026-01-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('exam_type', models.CharField(choices=[('laboratorio', 'Laboratorio'), ('imagen', 'Imagen diagnóstica'), ('especialista', 'Consulta especialista')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='exams/')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exam',
            },
        ),
    ]
