# Generated by Django 6.0.1 on 2026-01-29 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('examen_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_examen', models.CharField(choices=[('laboratorio', 'Laboratorio'), ('imagen', 'Imagen diagnóstica'), ('especialista', 'Consulta especialista')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='examenes/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes', to='doctor.doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='user.user')),
            ],
            options={
                'db_table': 'examen',
            },
        ),
    ]
