# Generated by Django 6.0.1 on 2026-03-16 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('register_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=3, null=True)),
                ('municipality_code', models.CharField(max_length=5, null=True)),
                ('territory_zone_code', models.CharField(max_length=2, null=True)),
                ('disability', models.CharField(max_length=2, null=True)),
                ('consecutive', models.CharField(max_length=7, null=True)),
                ('country_origin_code', models.CharField(max_length=3, null=True)),
                ('sex_code', models.CharField(max_length=1, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('mobile_number', models.CharField(max_length=20, null=True)),
                ('civil_status', models.CharField(max_length=50, null=True)),
                ('occupation', models.CharField(max_length=50, null=True)),
                ('service_provider_code', models.CharField(max_length=50, null=True)),
                ('attention_starting_date', models.DateField(null=True)),
                ('authorization_number', models.CharField(max_length=30, null=True)),
                ('record_code', models.CharField(max_length=10, null=True)),
                ('service_group_mode', models.CharField(max_length=2, null=True)),
                ('service_group', models.CharField(max_length=2, null=True)),
                ('service_code', models.CharField(max_length=4, null=True)),
                ('health_technology_goal', models.CharField(max_length=2, null=True)),
                ('diabetes', models.BooleanField(null=True)),
                ('cancer', models.BooleanField(null=True)),
                ('alcohol_consumption', models.BooleanField(null=True)),
                ('smoker', models.BooleanField(null=True)),
                ('drug_use', models.BooleanField(null=True)),
                ('job', models.TextField(null=True)),
                ('occupational_risk', models.TextField(null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor')),
                ('patient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patient')),
            ],
            options={
                'db_table': 'register',
            },
        ),
    ]
