# Generated by Django 6.0.1 on 2026-03-26 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('register_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('disability', models.CharField(max_length=2, null=True)),
                ('diabetes', models.BooleanField(null=True)),
                ('cancer', models.BooleanField(null=True)),
                ('alcohol_consumption', models.BooleanField(null=True)),
                ('smoker', models.BooleanField(null=True)),
                ('drug_use', models.BooleanField(null=True)),
                ('occupational_risk', models.TextField(null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor')),
                ('patient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patient')),
            ],
            options={
                'db_table': 'register',
            },
        ),
    ]
