# Generated by Django 6.0.1 on 2026-03-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='alcohol_consumption',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='cancer',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='diabetes',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='disability',
            field=models.BooleanField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='drug_use',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='occupational_risk',
            field=models.TextField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='smoker',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
