# Generated by Django 6.0.1 on 2026-04-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_register_alcohol_consumption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='occupational_risk',
            field=models.TextField(blank=True, null=True),
        ),
    ]
