# Generated by Django 6.0.1 on 2026-02-03 13:46

import apps.exam.api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('exam_type', models.CharField(choices=[('laboratorio', 'Laboratorio'), ('imagen', 'Imagen diagnóstica'), ('especialista', 'Consulta especialista')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to=apps.exam.api.models.exam_file_path)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.history')),
            ],
            options={
                'db_table': 'exam',
            },
        ),
    ]
