# Generated by Django 6.0.1 on 2026-03-16 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0001_initial'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.history'),
        ),
    ]
