# Generated by Django 6.0.1 on 2026-03-16 03:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason_consultation', models.TextField(null=True)),
                ('actual_disease', models.TextField(null=True)),
                ('physical_examination', models.TextField(null=True)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(200)])),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(3)])),
                ('heart_rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(220)])),
                ('respiratory_rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(25)])),
                ('key_findings', models.TextField(null=True)),
                ('main_diagnostic', models.TextField(null=True)),
                ('differential_diagnostic', models.TextField(null=True)),
                ('requested_exams', models.TextField(null=True)),
                ('programmed_procedures', models.TextField(null=True)),
                ('interconsultation', models.TextField(null=True)),
                ('follow_up_recommendations', models.TextField(null=True)),
                ('disability', models.TextField(null=True)),
                ('follow_up_plan', models.TextField(null=True)),
                ('prescription_details', models.TextField(null=True)),
                ('send_email', models.BooleanField(default=False)),
                ('cause_consultation', models.CharField(max_length=2, null=True)),
                ('main_diagnostic_code', models.CharField(max_length=25, null=True)),
                ('secondary_diagnostic_code', models.CharField(max_length=25, null=True)),
                ('third_diagnostic_code', models.CharField(max_length=25, null=True)),
                ('fourth_diagnostic_code', models.CharField(max_length=25, null=True)),
                ('service_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('income_concept', models.CharField(max_length=2, null=True)),
                ('payment_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fev_number', models.CharField(max_length=2, null=True)),
                ('previous_diseases', models.TextField(null=True)),
                ('previous_surgeries', models.TextField(null=True)),
                ('hospitalization', models.TextField(null=True)),
                ('allergies', models.TextField(null=True)),
                ('medicines', models.TextField(null=True)),
                ('immunization', models.TextField(null=True)),
                ('gynecologic_conditions', models.TextField(null=True)),
                ('obstetric_conditions', models.TextField(null=True)),
                ('psychiatric_conditions', models.TextField(null=True)),
                ('genetic_diseases', models.TextField(null=True)),
                ('vascular_diseases', models.TextField(null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor')),
            ],
            options={
                'db_table': 'history',
            },
        ),
    ]
