# Generated by Django 6.0.1 on 2026-03-26 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0001_initial'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.register'),
        ),
    ]
