# Generated by Django 6.0.1 on 2026-04-01 02:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='allergies',
            new_name='consultation_reason',
        ),
        migrations.RemoveField(
            model_name='history',
            name='age',
        ),
        migrations.RemoveField(
            model_name='history',
            name='cause_consultation',
        ),
        migrations.RemoveField(
            model_name='history',
            name='differential_diagnostic',
        ),
        migrations.RemoveField(
            model_name='history',
            name='disability',
        ),
        migrations.RemoveField(
            model_name='history',
            name='fev_number',
        ),
        migrations.RemoveField(
            model_name='history',
            name='follow_up_recommendations',
        ),
        migrations.RemoveField(
            model_name='history',
            name='fourth_diagnostic_code',
        ),
        migrations.RemoveField(
            model_name='history',
            name='genetic_diseases',
        ),
        migrations.RemoveField(
            model_name='history',
            name='gynecologic_conditions',
        ),
        migrations.RemoveField(
            model_name='history',
            name='hospitalization',
        ),
        migrations.RemoveField(
            model_name='history',
            name='immunization',
        ),
        migrations.RemoveField(
            model_name='history',
            name='income_concept',
        ),
        migrations.RemoveField(
            model_name='history',
            name='interconsultation',
        ),
        migrations.RemoveField(
            model_name='history',
            name='key_findings',
        ),
        migrations.RemoveField(
            model_name='history',
            name='main_diagnostic',
        ),
        migrations.RemoveField(
            model_name='history',
            name='main_diagnostic_code',
        ),
        migrations.RemoveField(
            model_name='history',
            name='medicines',
        ),
        migrations.RemoveField(
            model_name='history',
            name='obstetric_conditions',
        ),
        migrations.RemoveField(
            model_name='history',
            name='payment_value',
        ),
        migrations.RemoveField(
            model_name='history',
            name='prescription_details',
        ),
        migrations.RemoveField(
            model_name='history',
            name='previous_diseases',
        ),
        migrations.RemoveField(
            model_name='history',
            name='previous_surgeries',
        ),
        migrations.RemoveField(
            model_name='history',
            name='programmed_procedures',
        ),
        migrations.RemoveField(
            model_name='history',
            name='psychiatric_conditions',
        ),
        migrations.RemoveField(
            model_name='history',
            name='reason_consultation',
        ),
        migrations.RemoveField(
            model_name='history',
            name='requested_exams',
        ),
        migrations.RemoveField(
            model_name='history',
            name='secondary_diagnostic_code',
        ),
        migrations.RemoveField(
            model_name='history',
            name='send_email',
        ),
        migrations.RemoveField(
            model_name='history',
            name='service_cost',
        ),
        migrations.RemoveField(
            model_name='history',
            name='third_diagnostic_code',
        ),
        migrations.RemoveField(
            model_name='history',
            name='vascular_diseases',
        ),
        migrations.AddField(
            model_name='history',
            name='abdominal_findings',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='abdominal_perimeter',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='history',
            name='analysis',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='cardiac_system',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='central_nervous_findings',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='central_nervous_system',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='chest_findings',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='chest_system',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='clinical_orders',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='consciousness_status',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='diagnosis',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='diastolic_pressure',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='digestive_system',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='extremities_findings',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='extremities_system',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='eyes_findings',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='eyes_system',
            field=models.TextField(default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='general_status',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='genitourinary_findings',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='genitourinary_system',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='head_findings',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='head_perimeter',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='history',
            name='head_system',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='hydration_status',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='imc',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='history',
            name='mental_findings',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='mouth_findings',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='neck_findings',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='neck_system',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='other_findings',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='other_system',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='otolaryngology_findings',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='otolaryngology_system',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='pulmonary_system',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='respiratory_status',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='skin_findings',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='skin_system',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='systolic_pressure',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='temperature',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='heart_rate',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(220)]),
        ),
        migrations.AlterField(
            model_name='history',
            name='height',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='history',
            name='physical_examination',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AlterField(
            model_name='history',
            name='respiratory_rate',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='history',
            name='weight',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
