# Generated by Django 6.0.1 on 2026-04-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_rename_allergies_history_consultation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='issue_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
