# Generated by Django 6.0.1 on 2026-04-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_history_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='eyes_system',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
    ]
