# Generated by Django 6.0.1 on 2026-04-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_alter_history_eyes_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='actual_disease',
        ),
        migrations.AddField(
            model_name='history',
            name='current_illness',
            field=models.TextField(null=True),
        ),
    ]
