# Generated by Django 6.0.1 on 2026-04-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_remove_history_actual_disease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='family_history',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='patient_progress',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AddField(
            model_name='history',
            name='personal_history',
            field=models.TextField(blank=True, default='Sin alteraciones'),
        ),
        migrations.AlterField(
            model_name='history',
            name='follow_up_plan',
            field=models.TextField(blank=True, default='Sin seguimiento'),
        ),
    ]
