# Generated by Django 6.0.1 on 2026-03-28 05:56

from django.db import migrations

def seed_user_types(apps, schema_editor):
    UserType = apps.get_model('user_type', 'UserType')
    UserType.objects.get_or_create(name='doctor')
    UserType.objects.get_or_create(name='patient')
    UserType.objects.get_or_create(name='admin')

class Migration(migrations.Migration):

    dependencies = [
        ('user_type', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_user_types),
    ]