# Generated by Django 6.0.1 on 2026-03-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_type', '0002_seed_user_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
