# Generated by Django 6.0.1 on 2026-03-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100, null=True)),
                ('sex_code', models.CharField(max_length=1, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('pob', models.CharField(max_length=100, null=True)),
                ('occupation', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
