# Generated by Django 6.0.1 on 2026-03-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('affiliation_type', models.CharField(max_length=2, null=True)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
