# Generated by Django 6.0.1 on 2026-04-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='civil_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='religion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
