# Generated by Django 6.0.1 on 2026-01-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dni',
            new_name='id_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='dni_type',
            new_name='id_type',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='names',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='surname',
            new_name='surnames',
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
