# Generated by Django 6.0.1 on 2026-01-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id_doctor', models.BigAutoField(primary_key=True, serialize=False)),
                ('tarjeta_profesional', models.CharField(max_length=100, null=True)),
                ('especializacion', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'Doctor',
            },
        ),
    ]
